import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html
        lang="en"
        className={clsx("scroll-smooth  antialiased", inter.variable)}
      >
        <body className="flex h-full bg-white flex-col">{children}</body>
      </html>
    </>
  );
}
